#DATABASE Configuration
DATABASE_HOST		= "127.0.0.1"
DATABASE_USER		= "root"
DATABASE_PASSWORD	= ""
DATABASE_NAME 		= "BASE_SEGUIMIENTO"

#CONTRACTS TYPE
CONTRACT_TYPE_FIRME			= 0
CONTRACT_TYPE_PROVISIONAL	= 1

#AREAS
AREA_CONTROL_NAME			= "Administrador"
AREA_CONTROL_PASS			= "Administrador"
AREA_COMERCIAL_NAME			= "Comercial"
AREA_COMERCIAL_PASS			= "Comercial"
AREA_ABASTECIMIENTOS_NAME	= "Abastecimientos"
AREA_ABASTECIMIENTOS_PASS	= "Abastecimientos"
AREA_DESARROLLO_NAME		= "Desarrollo"
AREA_DESARROLLO_PASS		= "Desarrollo"
AREA_INGENIERIA_NAME		= "Ingenieria"
AREA_INGENIERIA_PASS		= "Ingenieria"
AREA_PLANIFICACION_NAME		= "Planificacion"
AREA_PLANIFICACION_PASS		= "Planificacion"